dpa99c/cordova-plugin-firebasex

- README.md
> Just updating the readme

- FUNDING.yml
This will be my kind of donation to this nice fork !
Have a nice week, thank you for letting me build my cordova project ! :D
> Integrate with github funding/donation system ;)

- scripts/lib/utilities.js
> Fix for short attribute in name tag

- scripts/after_prepare.js
This will fix the issue if there is a '&' in the app name.
> fix & in the app name

- README.md
> docs(readme): fix onMessageReceived code sample

- README.md
> fix(docs): code sample fix

- types/index.d.ts
Allow to create notification channels with descriptions, which was described at documentation, but the object IChannelOptions did not consider that option, once it hasn't the description attribute.
> Added description to IChannelOptions

- README.md
Update documentation code to create a channel. The previous instruction was not able to change light color because JAVA can't convert from hexadecimal string to integer. The result was always -1.
> Change doc - parsing channel color to integer

- types/index.d.ts
Added the missing `onApnsTokenReceived` method definition in `types/index.d.ts`.
n/a
n/a
> Added onApnsTokenReceived method in types

- README.md
Some code snippets didn't have proper syntax highlighting, so I added it where needed.
I also improved the usage example using Ionic 4. Most importantly, I specified that you had to register the plugin in an NgModule as a provider. I found that this was a question asked in issue #245 and [in this StackOverflow question](https://stackoverflow.com/questions/59134950/nullinjectorerror-no-provider-for-firebasex-in-ionic-4-firebasex) and several conflicting answers have been given.
n/a
n/a
> Add more syntax highlighting, better Ionic 4 examples.

- README.md
- src/android/FirebasePlugin.java
- src/ios/FirebasePlugin.m
- www/firebase.js
Added filters to collection, to download only necessary documents from firestore.
fetchFirestoreCollection method need to be refactored in all app to add the filter argument. The filter value can be false or [] (Empty array) after collection name.
I tested in a working project and utilizing a page prepared to this test.
> BREAKING CHANGE: (Android, iOS) Filters for firestore collection (Changed fetchFirestoreCollection method).

- plugin.xml
Increase Firebase Pod to `6.22.0`. See #373
> Upgrade Firebase Pod to 6.22.0

- plugin.xml
Increase Firebase Pod to 6.22.0. See #453 (https://github.com/dpa99c/cordova-plugin-firebasex/issues/453#issuecomment-658458194)
> update firebase pod to v6.28.0

- README.md
Adds steps necessary to maintain CLI variant in package
Resolves #476
> Adds additional CLI documentation

- README.md
- src/android/FirebasePlugin.java
- src/ios/FirebasePlugin.h
- src/ios/FirebasePlugin.m
- types/index.d.ts
Add sms code localization method 
- [X ] Feature
- [X ] Documentation  changes
Bugfixes:
- [X ] Exhaustive testing has been carried out for the new functionality
- [X ] Regression testing has been carried out to ensure no existing functionality is adversely affected
same PR added to cli_build
> Implementation of Firebase setLanguageCode method

- src/ios/FirebasePlugin.m
> Fix save config settings

- src/android/FirebasePlugin.java
This changes is only needed for Android since IOS's deserialization
from JSON to NSDictionary correctly convert a JSON that contains
a JSONArray and JSONObjects.
Bugfixes:
This PR address this issue https://github.com/dpa99c/cordova-plugin-firebasex/issues/491
We are using this PR in our project and we have used it in the last couple of months without any issues.
> Modify logEvent to recognize JSONArray and JSONObject in Android.

- README.md
Informing that the eventName parameter of the logEvent function does not allow dots in the string. Took me some time debugging to find this out.
Bugfixes:
> Adding note for analitics logEvent function

- src/android/FirebasePlugin.java
Bugfixes:
Adds a fix for setting sound per channel on Android, the logic was wrong and was causing sound to not be set properly as requested
> (Android) Fix sound configuration per channel

- src/ios/FirebasePlugin.m
(iOS) Added to sanitiseFirestoreDataDictionary types: Array, Timestamp, Number NaN and Number Infinity
Bugfixes:
Now types like Array, Timestamp, NaN and Infinity work like android
Local and production testing
Project available only to limited number of users.
> (iOS) Added types to sanitiseFirestoreDataDictionary

- README.md
This behavior confused me and it would have helped me if I knew it in advance, so hoping this might help someone else.
Bugfixes:
> Add note about Crashlytics behavior

- plugin.xml
> (Android) Feat: add android:exported element

- README.md
Bugfixes:
fix wrong parameter names for setUserProperty in readme file
- [x ] No
> fix setUserProperty parameters in README.md

- README.md
- src/android/FirebasePluginMessagingService.java
Bugfixes:
Improved notification image support and fixed error that did not show the notification image when the app was in the foreground.
Fix: https://github.com/dpa99c/cordova-plugin-firebasex/issues/202
Tested with and without the new variables when the app is closed, in foreground and background in the Android Studio emulator.
> (Android) Fix/Feat: Improved notification image support

- types/index.d.ts
Bugfixes:
This PR adds a type for authenticateUserWithEmailAndPassword in index.d.ts. authenticateUserWithEmailAndPassword is an existing function that was missing from the types.
This PR does not change any functionality. It adds a missing type definition.
This PR does not change any functionality. It adds a missing type definition.
The changes in this PR have been used in a production app available on both the App Store and Google Play Store.
> Add missing type for authenticateUserWithEmailAndPassword

- types/index.d.ts
Bugfixes:
Just fixed a return type of method in type definition file.
Before change, typescript compilation was failing with following error. After change compilation was successful.
```
ERROR in cordova/plugins/cordova-plugin-firebasex/types/index.d.ts(111,5):
TS7010: 'didCrashOnPreviousExecution', which lacks return-type annotation, implicitly has an 'any' return type.
```
> Fix: correct return type of a method

- README.md
- src/android/FirebasePlugin.java
- src/ios/FirebasePlugin.m
- types/index.d.ts
- www/firebase.js
- add settings parameters to types/index
- add actionCodeSettings as a command argument
- use parameters for the actionCodeSettings values in both ios and android
- update readme.md
Bugfixes:
This change adds supports for including the action code settings that allows you to add certain parameters to the verification email link. e.g opening the link on mobile vs opening the link in the mobile app
This PR has been tested with sending verification emails with various settings.
This PR has been tested without including actionCodeSetting Parameters. The email verification function still worked.
The changes in this PR have been used in a production app available on …
> include actionCodeSettings in the sendUserEmailVerification function

- src/android/FirebasePluginMessagingService.java
Bugfixes:
When using notifications without image attribute, exeception is thrown: _java.lang.NullPointerException: Attempt to invoke virtual method ‘java.lang.String [android.net](http://android.net/).Uri.toString()’ on a null object reference_
This PR checks image not being null before calling `toString()` on it.
> Fix null pointer exception when missing notification image

- README.md
- src/android/FirebasePlugin.java
- src/ios/FirebasePlugin.h
- src/ios/FirebasePlugin.m
- www/firebase.js
…urns all claims
To add the ability to get custom claims for the user
https://firebase.google.com/docs/auth/admin/custom-claims#android
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GetTokenResult#getClaims()
getClaims has been test on both ios and android, both when a user is signed in and when a user is signed out. 
In both android and ios, testing was done on the auth code. Logging in and out with different providers, updating the user's email, and using a auth emulator.
> Feature: Add support for getClaims

- types/index.d.ts
> Correctly declare FirebasePlugin as global #715

- types/index.d.ts
Add type definitions for `reloadCurrentUser` and update `getCurrentUser`
Are any fields optional?
> Add type definitions for reloadCurrentUser

- src/android/FirebasePluginMessagingService.java
Bugfixes:
Fix the error that produces no notifications are received on Android 12 and above if the Android SDK target is 31 and above #746
> (android) fix no notifications on Android 12 and above, Non-fatal Exception: java.lang.IllegalArgumentException

- types/index.d.ts
Android:
https://github.com/dpa99c/cordova-plugin-firebasex/commit/43f04965979d4e53de687887ec87ba9e2d22b550  
IOS:
https://github.com/dpa99c/cordova-plugin-firebasex/commit/24b77da8a324ac12299e74d61850b77c02b51ca3
- [ x ] Bugfix
- [ x ] Feature
> feat(types): add support for lastUpdate and created

- README.md
- docs/IOS_NOTIFICATION_SERVICE.md
- docs/NotificationService.swift
Bugfixes:
I have added information about the `IOS_NOTIFICATION_SERVICE.md` in the `README.md` and corrected some errors in the docs.
> (ios) docs: Update README.md with the link to IOS_NOTIFICATION_SERVICE.md

- README.md
Bugfixes:
Update to documentation related to server side validation of id token returned by `authenticateUserWithGoogle()`.
n/a
n/a
> add server side verification documentation to authenticateUserWithGoogle

- README.md
typescript wrapper link change to correct
> (doc) Update ionic ts wrapper link

- src/android/build.gradle
Bugfixes:
This PR change version on dependencies:
com.android.tools.build:gradle to 7.4.2
com.google.gms:google-services to 4.3.15
I tested on my environment with new version of Cordova Android 12.
It now build as expected
Fix Issue #807
> use cordova-android config variable version, Fix #807

- README.md
> (ios) docs: Typo fix

- plugin.xml
- scripts/ios/before_plugin_install.js
Bugfixes:
As mentioned [here](https://firebase.google.com/docs/ios/setup#:~:text=For%20apps%20that%20use%20CocoaPods%2C%20the%20Firebase%20pod%20is%20deprecated%20in%20v9.0%20and%20higher.%20Instead%2C%20you%20need%20to%20reference%20product%20pods%20directly%20in%20your%20Podfile%20(for%20example%2C%20FirebaseCore%20instead%20of%20Firebase/Core%20and%20FirebaseFirestore%20instead%20of%20Firebase/Firestore)), the `Firebase` Pod is deprecated since v9.0, and projects should use the product pods directly. 
This incidentally fixes an issue with the `IOS_USE_PRECOMPILED_FIRESTORE_POD`, which currently does not work due to the CocoaPods error below:
`[!] There are …
> Use product CocoaPods for firebase packages

- plugin.xml
Bugfixes:
Fix ios build, by adding FirebaseAnalytics pod, see https://github.com/dpa99c/cordova-plugin-firebasex/issues/847
Local testing of an iOS build.
> (iOS) fix: add FirebaseAnalytics pod

- README.md
Clarify documentation around `config-file` and push notification permissions.
> Add note about xmlns:android attribute for config.xml

- www/firebase.js
Bugfixes:
Didnt run regression but might not be necessary for the change type.
The current release of this plugin fails with the default version of Chrome that comes with SDK 24 & 25.
This issue is cause by the trailing comma in the function parameters. [Support for trailing commas in function parameters was adde in Chrome 58](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#browser_compatibility). 
SDK 24: WebView 53 (fails)
SDK 25: WebView 55 (fails)
SDK 26: WebView 58 (works)
Since the latest Cordova Android's minimum SDK support 24, and the type of change is minor, I thought maybe its OK to request.
Manually deleting the …
> fix(android): issue w/ trailing comma in SDK 24 & 25's default Chrome WebView

- README.md
Explain how to enable Analytics debug mode on the documentation.
On Merge this close #785
> Add information to enable the Analytics debug_mode to the README.md

- docs/IOS_NOTIFICATION_SERVICE.md
> (ios) docs: Update IOS_NOTIFICATION_SERVICE.md

- scripts/lib/utilities.js
> (cordova): fix invalid cordova hook interface use, fix #908

- src/ios/AppDelegate+FirebasePlugin.m
https://firebase.google.com/docs/analytics/debugview
https://github.com/firebase/firebase-ios-sdk/blob/e8c71d1f7f3363b488f9f2045845afbb82fd016a/FirebaseCore/Sources/FIRLogger.m#L75
https://github.com/firebase/firebase-ios-sdk/issues/13640#issuecomment-2408404500
Bugfixes:
> feat(ios): Turn on debug view for debug builds

- README.md
- scripts/ios/after_plugin_install.js
- scripts/ios/before_plugin_uninstall.js
- scripts/ios/helper.js
> fix: Integration with GoogleTagManager
