dpa99c/cordova-plugin-firebasex

plugin.xml

Autoident file and upgrade tags from "framework" to "pod", everytime i was trying to install, i received the message that "framework" was deprecated and will be removed soon, when i changed from the original plugin to this fork, the Podfile was always empty, and the build generates an error "could not find Firebase.h", upgrading to "pod" tag, it generates the Podfile normally and no build error. This may remove support to old versions, but at any time Cordova will finally remove the use of this tag.

modify plugin.xml

---

README.md

Hi Dave,
I reused the Cocoapods chapter of your README to submit a PR to [cordova-plugin-googleplus#615](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/615) where I suggest to use Cocoapods dependencies too.
The least I could do was to correct 2-3 typo ;)

doc: fix README Cocoapods typo

---

scripts/android/helper.js

This pull request is for fixing the warnings:
> Configure project :app
+-----------------------------------------------------------------
| cordova-android-play-services-gradle-release: +
+-----------------------------------------------------------------
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced …

Update dependencies Fabric

---

plugin.xml

This fixes a bunch of problems with iOS13, like [this one](https://github.com/firebase/firebase-ios-sdk/issues/3365). Especially some problems with calling UIKit methods on a background thread (which can lead to crashes) were fixed since version `6.3.0`.
The changelog for the different iOS releases can be found [here](https://firebase.google.com/support/release-notes/ios).
Personally I only use Firebase/Analytics in my projects so I only tested this functionality, no problems so far, warnings, freezes (in dev mode), crashes on iOS13 are gone.
For upgrading it may be required to update the cocoapods repo before adding the plugin with the new versions: run `pod repo update` in your terminal to do so.

Update firebase ios pods to latest versions

---

package.json
types/index.d.ts

I tried to declare all methods, but I can wrong. Feel free to point out errors.
Thank you!

feat(ts): add ts declaration

---

README.md
src/android/FirebasePlugin.java

I notice that android custom channel supports additional description. 😉 
* added [`description`](https://developer.android.com/reference/android/app/NotificationChannel.html?hl=RU#setDescription(java.lang.String)) option on channel creating 
* updated readme

feat(android): add `description` option for channel

---

plugin.xml

While attempting to run `pod install`, the default spec repo is killing my build times due to its size. CocoaPods [new CDN](http://blog.cocoapods.org/CocoaPods-1.8.0-beta/) to fix this issue is being overridden by the plugin.
I have confirmed that this change significantly reduces `pod install` time, and still allows proper installation.

Update CocoaPods spec url to new CDN

---

README.md

Updated example snippet code to set default android icon in config.xml with the `<config-file>` block. Parent tag must contain "**/manifest/application**" value to avoid android Manifest overwrite error from cordova.
This resolve [this issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/85) reported as cordova bug [here](https://github.com/apache/cordova-android/issues/809) and it's not necessary use cordova-custom-config plugin

Updated snippet code default android icon

---

src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m

Add a workaround to properly handle the APNS format token change.

iOS 13 APNS format token change 

---

scripts/after_prepare.js

I ran into another form of issue https://github.com/dpa99c/cordova-plugin-firebasex/issues/101 today. The `config.xml` for my Cordova app didn't have any platform elements yet, due to which a promise in the `after_prepare.js` script didn't resolve.
As far as I can see the check for the presence of platform elements is superfluous, so I removed it.

Remove check for presence of platform in config.xml

---

scripts/after_prepare.js

As described in #217 the after_prepare script hangs with error `.forEach is not a function`. This happens either if there is only one plugin configuration in the config.xml or if a plugin configuration only has one variable. This is due to `config.widget.plugin` or `plugin.variable` not being arrays in this cases. This PR makes sure that both always are arrays.
Tested with different config.xml scenarios.
Tested with different config.xml scenarios.
The open PR #213 (which I discovered just now before submitting mine) does not fix both cases.

Fix .forEach is not a function

---

scripts/ios/after_plugin_install.js

When installing plugin for iOS, the plugin doesn't add custom run script required for Crashlytics in Xcode generated project. This PR fixes that retrieving correctly the Xcode project path.

Fixed retrieving Xcode project path

---

src/android/FirebasePlugin.java

fix for error: local variable is accessed from within inner class; needs to be declared final;

local variable is accessed from within inner class

---

src/android/build.gradle

To fix an error "Cannot add extension with name 'googleServices', as there is an extension already registered with that name".

[Android] Add check google-services plugin does not exist

---

plugin.xml

Added missing GoogleTagManager Cocoapods dependency (for iOS).
Expected behaviour was having GTM support for iOS out-of-the-box.
Current PR fixes that adding missing Cocoapods dependency to plugin.xml (seamless with Android configuration).
Creating and running iOS App with support for GTM / Google Analytics.

Added missing Google Tag Manager Pod for iOS

---

README.md
plugin.xml

Add firebase InAppMessaging as described in he link:
https://firebase.google.com/docs/in-app-messaging/get-started?platform=android
Functional testing, using emulators and real devices
Using emulators and real devices

Added InAppMessaging for iOS and Android

---

README.md

Fixes broken markdown link in the README
Markdown is displayed correctly

docs: fix broken markdown link for strip debug symbols

---

README.md
src/android/FirebasePlugin.java
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m
types/index.d.ts
www/firebase.js

Added signInWithCustomToken and signInAnonymously firebase authentication types.
I tested with a real projeto app.fretecorreios.com.
The version with this version of firebasex is only internal yet.
No breaking changes for this PR.
I tested with a real projeto app.fretecorreios.com.
The version with this version of firebasex is only internal yet.
No bugsfor this PR.

Added signInUserWithCustomToken AND signInUserAnonymously auth methods

---

README.md

createChannel suggestion for multiple sounds

---

README.md
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m

getInfo on iOS should return similar (to android) info object on success callback.
getInfo implementation for iOS
Ran on device to verify the implementation return desired result w/o crashes.
should not impact existing functionality

Get info fori os

---

types/index.d.ts

Fix of a missing return type
Just fixed a return type of method in type definition file.
Before change, typescript compilation was failing with following error. After change compilation was successful.
```
Error in cordova/plugins/cordova-plugin-firebasex/types/index.d.ts(114,5):
TS7010: 'logError', which lacks return-type annotation, implicitly has an 'any' return type.
```

Fix: correct return type of a method

---

src/ios/AppDelegate+FirebasePlugin.m

We ran into a problem with a configuration using the firebasex and firebase-analytics plugins together. The latter was performing `[FIRApp configure]` during the `[self application:application...` super call at the top of this function, which caused an exception when FIRApp was configured again by this plugin. This exception bypassed the remainder of the code block and prevented our app from receiving push notification data when the terminated (not just backgrounded) iOS app was opened by tapping a notification.
Reconfiguration of FIRApp causes an exception in `appWasConfiguredTwice`. Another plugin (firebase-analytics) was configuring FIRapp already, so this …

Prevent reconfiguration causing exception

---

package.json
scripts/ios/helper.js
src/ios/FirebasePlugin.m

Currently it is possible for the 3 collections (analytics collection, performance collection, crashlytics collection) to get into an inconsistent state. 
This is possible because when setting the flags an error is thrown if the plugins own state already matches the value the user would like to set (e.g. "Analytics data collection is already set to enabled"). However it is possible the Firebase SDK was already used before the plist config flags were introduced which could lead to the following scenario:
- In the old SDK the user has enabled the analytics collection (SDK is in state enabled, no plist config yet) ✅
- App is updated to new plugin version with all …

(iOS/Android): avoid collection state getting out of sync, remove restriction to override plist defaults

---

src/ios/FirebasePlugin.m

Prevent `escapeJavascriptString` method to escape already escaped symbols
Fixes #401
Sending already escaped json as `data` property
Tested in in-house project which uses FCM functionality of this plugin – no regressions

(iOS) Fix escaping already escaped json

---

README.md
scripts/after_prepare.js

- [ x] Feature
This PR adds possibility to set custom location for `google-services.json` and `GoogleService-Info.plist` using ANDROID_KEY and IOS_KEY variables.
- [ x] No

Set custom locations for platform config files using plugin variables

---

README.md
src/android/FirebasePlugin.java
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m

Closes #434.
Adds support for Firebase Crashlytics `didCrashOnPreviousExecution` & `setCustomKey`
- [x ] No
Tested on Android Phone and iOS iPad
Ensured push notifications and crashlytics logging continued to work.

Added support for Crashlytics didCrashOnPreviousExecution & setCustomKey

---

src/android/build.gradle

Bugfixes:
Fix issue described in https://github.com/dpa99c/cordova-plugin-firebasex/issues/536
We are using `AfterEvaluate` instead of [cordova android guideline](https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html) because if we use it it will introduce a break change. Older cordova android version will be broken.
In next major version it could be good remove this lines and use:
```
<config-file target="config.xml" parent="/*">
<preference name="GradlePluginGoogleServicesEnabled" value="true" />
<preference name="GradlePluginGoogleServicesVersion" value="4.2.0" />
</config-file>
```
Used test project to test if it's correct. Steps to reproduce inside git issue

fix: Using AfterEvaluate to postpone the execution of apply plugin com.google.gms.google-services

---

src/android/FirebasePlugin.java

Bugfixes:
This PR has the purpose of fix a bug with NaN values registered on firestore.
If you try to deserialize NaN values will receive the following exception: java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
Changing the code to use GsonBuilder.serializeSpecialFloatingPointValues() the JSONObject class return another exception: org.json.JSONException: Forbidden numeric value: NaN
Than with GsonBuilder.registerAdapter I transformed the special NaN and Infinite numbers to string.
Yes, this is working in a live project. …

(Android) Fix Gson serialization to NaN values

---

src/ios/FirebasePluginMessageReceiverManager.h

- [ X ] Bugfix
This is to commit the fix mentioned in #493 to the plugin directly, so that it will not need to be manually added every time a build is run. 
- [ X ] No
Test project is currently not building for what I think are unrelated reasons: 
```
'FirebaseCore/FirebaseCore.h' file not found.
Could not build module 'Firebase'
```
I have tested this fix on my own project, and it does fix the bug mentioned in #493.

Adding base class to to prevent iOS build error

---

README.md
src/android/FirebasePlugin.java
src/ios/AppDelegate+FirebasePlugin.m

- should allow to propagate the token to the web view layer and sign-in within both tiers (native and web)
Bugfixes:
It's a common case to authenticate on native layer and propagate idToken to the web view layer. After the sign-in process completes, the user will be signed in within both tiers, and we can use web specific sdks, as AngularFire for example, to handle Firebase account.
It's widely used on Cordova/Capacitor communities, as exposed by [Dayana Jabif (ionicThemes) on ionic forum](https://forum.ionicframework.com/t/help-how-do-i-integrate-native-firebase-google-login-with-my-capacitor-app/197601/2)
> I used …

feat(auth): add idToken on signIn w/ Google response

---

README.md
src/android/FirebasePluginMessagingService.java

Bugfixes:
Support has been added so that the plugin can show html in the body of the notification.
Related: https://github.com/dpa99c/cordova-plugin-firebasex/issues/666
Tested in the Android Studio emulator.

(Android) Feat: Support html attributes in body notifications

---

README.md
src/android/FirebasePlugin.java
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m
types/index.d.ts
www/firebase.js

This change adds support for the [Firebase Authentication emulator](https://firebase.google.com/docs/emulator-suite/connect_auth) which is part of the Firebase Local Emulator Suite. It allows authentication to be handled by a local emulator suite rather than a real Firebase project instance.
This PR has been tested with the useAuthEmulator function called after the FirebasePlugin has been initialized. It successfully connects and uses the configured authentication emulator for Firebase Authentication operations.
This PR has been tested without calling the useAuthEmulator function. All existing Firebase Authentication behaviour is unchanged.
The changes in this …

Support Firebase Authentication emulator

---

src/android/FirebasePlugin.java

Bugfixes:
This PR fetches the interim OAuthProvider when calling linkUserWithCredential. Without it, using OAuth based authentication before linking a user with a credential would fail. (e.g. using authenticateUserWithApple to retrieve a credential for linkUserWithCredential on Android would not successfully link the user with their Apple ID.)
This PR has been tested on an Android device using a real Apple ID, linked to an existing Firebase user.
This PR has been tested using Sign in With Google and sign in with email/password ahead of linking to an existing Firebase user.
The changes in this PR have also been used in a production app available on both the App Store and Google Play Store.

Use OAuthProvider when available during linkUserWithCredential

---

src/android/FirebasePlugin.java

Bugfixes:
This is to fix https://github.com/dpa99c/cordova-plugin-firebasex/issues/662 Where getCurrentUser could fail on android
Tested by including my fork of the plugin in our app, and getting the current user. Not just in dev but also in production.
The auth code has been throughly tested from tzappia's branch, but not based on your current dev build, with the other PRs recently merged. I will so some testing on it with those merged.
edit: Tested done on this branch, using the auth emulator and a pixel 6. I did not encounter any issues during testing.

Fix an error getting the providerId that could cause getCurrentUser to fail on android

---

src/ios/AppDelegate+FirebasePlugin.m
src/ios/FirebasePlugin.m

Bugfixes:
This PR fixes #730 by allowing CDVAppDelegate to properly capture incoming openURL events and pass them out to all plugins.

Cordova-compliant external URL handling

---

README.md
src/android/FirebasePlugin.java
src/ios/FirebasePlugin.m
www/firebase.js

Bugfixes:
The objective of this update is to add a Timestamp variable to the documents, giving the possibility of being able to filter the searches by date of creation or last modification.
I have tried to create documents and edit them in Firestore and it works without problems.

Added timestamp 'created' and 'lastUpdate' variables in Firestore functions

---

plugin.xml

The latest code expects that the pod for Firestore is the default. This change was included in `master` (at d1fb68a) but seems was lost in the merge to `cli_build`
d1fb68a - (iOS) Use standard pod for Firestore by default but add `IOS_USE_PRECOMPILED_FIRESTORE_POD` plugin variable to switch to using pre-built version.
Bugfixes:
Fix the `cli_build` branch to function as described in the README.
Technically I would call this a breaking change for the `cli_build` because effectively it changes the default behavior, despite it bringing the code inline with `master` functionality and the documentation.
Our builds dependent on the `cli_build` branch now work as …

(iOS) Use standard pod for Firestore by default - patch cli_build

---

plugin.xml
src/android/FirebasePluginMessagingService.java
src/android/OnNotificationReceiverActivity.java

Bugfixes:
Fix the issue that produces clicking on the notification does not open the app in Android 12+ if the app is in target SDK 31+ #763 
It has been tested to receive notifications and open notifications in Android 13 (SDK 33) and Android 11 (SDK 30)

(Android) fix: Notification opening app for Android 12 (#763)

---

src/ios/AppDelegate+FirebasePlugin.m

Add the authorization code to the credential object returned after authentication via Sign in with Apple.
No change to existing functionality.
Upon successful authorization using Sign in with Apple, this feature adds the field `authorizationCode` to the `didCompleteWithAuthorization` result.
The Authorization Code is a required piece of information for revoking a Sign in with Apple token, as mandated by Apple (June 30, 2022) when deleting a user's account.
The Firebase team are working on a solution to automatically revoke Sign in with Apple tokens when an account is deleted (ref: https://github.com/firebase/firebase-ios-sdk/issues/9906). In the meantime, giving …

Add the authorization code to the credential object returned after authentication via Sign in with Apple

---

src/android/FirebasePluginMessagingService.java

The purpose of this PR is to address #771 and add support for localization inside of the foreground push notifications.
Mainly, all this PR does is introduce support for the below keys and allows the sender of the notification to have foreground notifications with localized content, which prior to this PR was not supported. Previously the foreground notification would not display at all because the `body` and `title` were null when sending down only localized content.
Missing keys from the foreground notification check which are being added and supported:
- `title_loc_key`
- `title_loc_args`
- `body_loc_key`
- `body_loc_args`
This does not affect existing behavior as it only attempts to set the title and body if the …

Add support for Android push notification localization in foreground notifications

---

scripts/ios/before_plugin_install.js

Bugfixes:
Updates plugin.xml to use the precompiled version of FirebaseFirestore (if setting is enabled) on the first `pod install`

Use precompiled FirebaseFirestore on first pod install

---

src/ios/FirebasePlugin.m

Bugfixes:
Currently, calling `grantPermission` on ios while permissions have not been granted will cause received foreground notifications (notifications with `"notification_foreground": "true"`) to not be displayed until app is restarted. This seems to happen because the `grantPermission` function changes the notification center delegate if called and permissions have not been already granted:
https://github.com/dpa99c/cordova-plugin-firebasex/blob/ab660596f311fd9cb8fa70e0b1de9bb60ace25d6/src/ios/FirebasePlugin.m#L303-L310
Meanwhile the completionHandler for the permission request never sets this back to the original value
https://github.com/dpa99c/cordova-plugin-firebasex/blob/ab660596f3 …

(ios) Fix foreground notifications not being displayed after calling grantPermission when permissions haven't been previously granted

---

src/android/FirebasePluginMessagingService.java

Fix compile issue on API 34
Bugfixes:
None
None

Fix ambiguity between bigLargeIcon(Bitmap) and bigLargeIcon(Icon) on API 34

---

plugin.xml
scripts/ios/before_plugin_install.js
scripts/ios/helper.js
src/ios/AppDelegate+FirebasePlugin.m
src/ios/FirebasePlugin.h
src/ios/FirebaseWrapper.h

Bugfixes:
The switch to product pods (#811) broke builds because of the missing `Firebase.h` file. This adds `FirebaseWrapper.h` which replicates the behavior of that file from the top-level `Firebase` pod. 
It also removes some code that attempts to modify the `plugin.xml` file before the first `pod install` to use the pre-built Firestore, which was not functioning because Cordova reads the `plugin.xml` file into memory before firing that hook. 
NOTE: The precompiled Firestore flag still does not work because of the issue described here: https://github.com/invertase/firestore-ios-sdk-frameworks/issues/62

Fix plugin imports using product-level CocoaPods

---

README.md
plugin.xml
scripts/ios/helper.js
src/android/FirebasePlugin.java
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m
types/index.d.ts
www/firebase.js

Bugfixes:
GA4 now requires consent (EEA)
https://support.google.com/analytics/answer/14275483
Forked the firebasex test project and tested the consent functionality
https://github.com/pinguluk/cordova-plugin-firebasex-test

Add Consent Mode v2 (Android & iOS)

---

scripts/ios/helper.js

Bugfixes:
`cordova-ios` has changed the structure of the pbxproj file since 7.0.0. This fix will check for if the required shellscript build phase section is empty and create an empty object to avoid throwing an error.
Adding the `ios` platform using ios-cordova@7.1.0.
Adding the `ios` platform using ios-cordova@7.1.0.

fix(ios) handle pbxproj structure change

---

src/ios/FirebasePlugin.m

Bugfixes:
I had this pull request opened 6 months ago (https://github.com/dpa99c/cordova-plugin-firebasex/pull/883) and unfortunately you merged a few days ago just when I was messing around with "rawNonce" on the Google Authentication for iOS, to test a few things. 
You need this change, which basically reverts my pull request to the original state, otherwise the app crashes. The rawNonce is only used when logging in with Apple, as per the original pull request.

Removed unnecessary "rawNonce" from FirebasePlugin.m

---

src/android/FirebasePlugin.java
src/ios/AppDelegate+FirebasePlugin.m
src/ios/FirebasePlugin.h
src/ios/FirebasePlugin.m

New feature - Hold notifications when the app is in background and and call the app callback once back in foreground.
Bugfixes:
New message notifications, call the onMessageReceived callback. This might be important to handle new notifications by the app, especially data notifications. In both Android and iOS, the plugin is calling the onMessageReceived callback but when the application is in the background for more than 20-30 seconds, the callback does not execute.
In case of Android, when the app is not active (the main activity is closed), the callback is not valid as the WebView does not exist.
The plugin already implements a queue to hold any pending notifications until the app calls …

Handle notification callback in the background

---

scripts/lib/utilities.js

Bugfixes:
In the latest version trying to build a project that has no cordova-ios platform failed with the following error:
Error: Cannot find module 'cordova-ios'
Require stack:
- project\src-cordova\plugins\cordova-plugin-firebasex\scripts\lib\utilities.js
- project\src-cordova\plugins\cordova-plugin-firebasex\scripts\after_prepare.js
- C:\Users\sarantis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js
- C:\Users\sarantis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js
- C:\Users\sarantis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\plugman.js
- …

remove unused cordova-ios import that breaks projects without ios platform

---

src/android/FirebasePlugin.java

Current exception logging throws NPE. Change to Crashlytics log to properly handle these exceptions
A better exception handling
Bugfixes:
Handle exceptions as in other places of the plugin
None as the exception is only visible in logs

Handle notification exceptions

---

src/ios/FirebasePlugin.m

Anonymous account linking operation can fail if the credential is already associated with another account. A common case is, that you want to either link or sign in to an account. For most auth providers the first credential can be reused for the sign in operation. In case of Apple Auth, we receive an updated credential in the error.
The plugin would not handle that error correctly, so the user would have to go through double sign in popups in order to make that flow work
createAuthErrorResult would not handle the case of FIRAuthErrorCodeCredentialAlreadyInUse as it should- it would not save the updatedCredentials that are returned in the error and it did not pass them forward.
Saved the updatedCredentials and sent it forward.
Tested on my own …

Access to FIRAuthErrorUserInfoUpdatedCredentialKey on linkUserWithCredential auth/credential-already-in-use error

---

src/ios/FirebasePlugin.m

Forcing token refresh when calling getClaims on iOS. This is a default behavior in Android as well.
Bugfixes:
There was no way to force refresh the user's token on iOS, getClaims function would force refresh the token on Android, but not on iOS.
Now it force refreshes the token on iOS as well.
Tested on my project

Forcing token refresh when calling getClaims on iOS
